server:
  port: 8080
spring:
  application:
    name: authentication
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/${DB_DATABASE_NAME}?autoreconnect=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
    show-sql: false

  flyway:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_DATABASE_NAME}
    schemas: ${DB_SCHEMA_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
security:
  token:
    accessLifespan: ${ACCESS_TOKEN_LIFESPAN}
    refreshLifespan: ${REFRESH_TOKEN_LIFESPAN}
    secret: ${TOKEN_SECRET}
    cutoffDate: ${TOKEN_CUTOFF_DATE}
user:
  profile:
    image:
      maxSize: 2048
      allowedWidths: 400
      allowedHeights: 400