server:
  port: 8080
spring:
  application:
    name: authentication
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/auth_db?autoreconnect=true&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/auth_db
    schemas: auth_db
    user: root
    password: root