server:
  port: 8080
spring:
  application:
    name: authentication
  datasource:
    password:
    url:
    username:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: false

  flyway:
    url:
    schemas:
    user:
    password: